# Generated by Django 5.1.7 on 2025-03-18 01:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoteFrango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50, unique=True, verbose_name='Número do Lote')),
                ('data_producao_abate', models.DateField(verbose_name='Data de Produção/Abate')),
                ('granja_origem', models.CharField(max_length=100, verbose_name='Granja de Origem')),
                ('empresa_produtora', models.CharField(max_length=100, verbose_name='Empresa Produtora')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('orgao_inspecao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Órgão de Inspeção Sanitária')),
                ('resultados_analises', models.TextField(blank=True, null=True, verbose_name='Resultados de Análises')),
                ('prazo_validade', models.DateField(verbose_name='Prazo de Validade')),
                ('condicoes_conservacao', models.TextField(verbose_name='Condições de Conservação')),
                ('historico_vacinacao', models.TextField(blank=True, null=True, verbose_name='Histórico de Vacinação')),
                ('status_sanitario_granja', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Sanitário da Granja')),
                ('medidas_biosseguridade', models.TextField(blank=True, null=True, verbose_name='Medidas de Biosseguridade')),
                ('manejo_sanitario', models.TextField(blank=True, null=True, verbose_name='Manejo Sanitário')),
                ('densidade_alojamento', models.IntegerField(blank=True, null=True, verbose_name='Densidade de Alojamento (aves/m²)')),
                ('temperatura_galpao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Temperatura do Galpão (°C)')),
                ('umidade_galpao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Umidade do Galpão (%)')),
                ('sistema_ventilacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema de Ventilação')),
                ('iluminacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Iluminação')),
                ('acesso_agua_alimento', models.BooleanField(default=True, verbose_name='Acesso Adequado à Água e Alimento')),
                ('estrutura_galpao', models.TextField(blank=True, null=True, verbose_name='Estrutura do Galpão')),
                ('manejo_bem_estar', models.TextField(blank=True, null=True, verbose_name='Práticas de Manejo para Bem-Estar Animal')),
                ('tipo_racao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Ração')),
                ('abatedouro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Abatedouro')),
                ('certificacoes', models.TextField(blank=True, null=True, verbose_name='Certificações')),
                ('contato_duvidas', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contato para Dúvidas')),
            ],
            options={
                'verbose_name': 'Lote de Frango',
                'verbose_name_plural': 'Lotes de Frango',
                'ordering': ['-data_producao_abate'],
            },
        ),
    ]
